from enum import IntFlag

import comtypes.gen._14B95319_AEF9_492A_A878_CA18FEB1F5BF_0_1_7 as __wrapper_module__
from comtypes.gen._14B95319_AEF9_492A_A878_CA18FEB1F5BF_0_1_7 import (
    DNC_EXEC_MDI, DNC_CP_DIO_LEADERLENGTH, DNC_E_INVALID_PASSWORD,
    DNC_CP_SSH_IDENT, DNC_ACCESS_MODE_USR, DNC_TRIG_ON_CONDITION,
    DNC_CNC_TYPE_TNC128_NCK, _IJHDataAccessEvents, DNC_KEYACTION_DOWN,
    DNC_DATA_UNIT_AMPERE, IJHVirtualMachine,
    DNC_EVT_STATE_HOST_STOPPED, JHTest,
    DNC_POSSAMPLES_LOGGING_NONLINEAR_SAMPLED_WITH_BLOCK_END,
    DNC_CNC_TYPE_AR6000_NCK, DNC_TRIG_SAMPLE_ON_CHANGE,
    _DJHTestEvents, JHTraceSampleEnum, DNC_PRG_EVT_SELECTED,
    DNC_CP_LSV_DELAY, DNC_ACCESS_MODE_SCOPE, DNC_PRG_STS_INTERRUPTED,
    DNC_INTERFACE_JHDATAACCESS, JHDirectoryEntryEnum,
    DNC_TRACE_VARIABLE_ID_VNOM, JHErrorEntryEnum, IJHAxisPositionList,
    DNC_SPINDLE_STATE_TAPPING, DNC_INTERFACE_JHVIRTUALMACHINE,
    DNC_E_DIR_NOT_FOUND, DNC_CNC_TYPE_MANUALPLUS_NCK,
    DNC_TRACE_VARIABLE_ID_JNOM, DNC_E_DIR_REMOTE_LOCKED,
    DNC_ACCESS_MODE_AUTOMATIC, IJHAutomatic4, JHVersion,
    DNC_EXEC_OTHER, DNC32_E_FAIL_HANDLE, DNC32_E_NO_AUTODETECT,
    DNC_TRIG_SEQUENCE_AND_THEN, DNC_SW_TYPE_TNC_OTHER,
    DNC_STATE_MACHINE_IS_INITIALIZING, JHFileAttributes, IEventObject,
    DNC_TRIG_SAMPLE_ON_IPO, DNC_SW_TYPE_FS_MCU, DNC_E_DIR_NOT_EMPTY,
    DNC_E_DIR_NESTING, DNC_KEYACTION_DOWN_UP,
    DNC_EVT_STATE_HOST_AVAILABLE, IJHRemoteErrorEntry,
    DNC_ATTRIBUTE_LOCKED,
    DNC_POSSAMPLES_LOGGING_NONLINEAR_SAMPLED_WITH_BLOCK_END_WITH_AUX_AXES,
    DNC_INTERFACE_JHREMOTEERROR, DNC_DATAENTRY_PROPKIND_UPPER_BOUND,
    DNC_CNC_TYPE_GRINDPLUS640_NCK, IJHAxesPositionStreaming2,
    DNC_PRG_STS_NOT_SELECTED, _IJHMachineEvents2, JHTraceChannel,
    IJHAutomatic2, IJHLoggingInternal, IJHConnection,
    DNC_DATAENTRY_PROPKIND_BASE_ENTRY,
    DNC_EVT_STATE_MACHINE_AVAILABLE, DNC_SW_TYPE_TNC_OPT,
    DNC_ACCESS_MODE_HWSDATAACCESS, DNC_TRIG_ON_RISE,
    _IJHAxesPositionStreamingEvents, JHTraceSample,
    DNC_ACCESS_MODE_DSP, DNC_TRIG_ON_COND_LEQ,
    DNC_DATA_UNIT_METER_PER_SEC3, DNC_E_FILE_REMOTE_LOCKED,
    DNC_POSSAMPLES_MOTION_LINEAR, IJHTriggerList, IJHAutomatic3,
    DNC_CP_LSV_TX_TIMEOUT, DNC_ACCESS_MODE_USR_PRIVATE,
    DNC_SW_TYPE_SPLC, JHBreakCondition, DNC_E_FILE_FILENAME,
    DNC_PRG_EVT_CANCELED, DNC32_E_NOT_HANDLE, DNC_E_UTC_TO_LOCAL,
    DNC_E_NO_TRACING_ACTIVE, DNC_HANDLE, DNC_E_CANNOT_RESTORE_DEFAULT,
    DNC_E_UNABLE_TO_INSERT, DNC32_E_TIMEOUT_VAL, DNC_EXEC_HANDWHEEL,
    DNC_POSSAMPLES_LOGGING_SAMPLED, DNC_ACCESS_MODE_CFGDATAACCESS,
    DNC_ACCESS_MODE_GEOSIMDATAACCESS, DNC_SW_TYPE_FCL,
    DNC_TRIG_ON_COND_GEQ, DNC_E_DIR_REMOTE_NOT_FOUND, DNC_PROT_RPC,
    DNC_TRIG_ON_FALL, DNC_PRG_STS_ERROR, DNC_TRACE_VARIABLE_ID_IPODBG,
    DNC_CNC_TYPE_MILLPLUSIT, DNC_KEYACTION_UP, DNC_E_INVALID_CHANNEL,
    DNC32_E_NO_PORT, JHDataEntryProperty2Enum, DNC_DATA_UNIT_NONE,
    DNC_E_DIR_LOCKED, DNC_TRACE_VARIABLE_ID_ININT,
    DNC_ACCESS_MODE_SPLCDATAACCESS, DNC_E_DNC32FAILED, IJHPlc,
    DNC_TRACE_VARIABLE_ID_INOM, DNC_E_FILE_REMOTE_EXISTS,
    JHAutomaticEvents, DNC_EXEC_MANUAL, dispid, DNC_CNC_TYPE_TNC7_NCK,
    DNC_TRIG_INTERFACE_CONDITION, DNC_EVT_STATE_WAIT_PERMISSION,
    IJHDirectoryEntryList, DNC_E_ALL_CONNECTIONS_IN_USE,
    DNC_E_TOO_MANY_ELEMENTS, IJHDirectoryEntry, DNC_SW_TYPE_TNC_ICTL3,
    IJHDataAccess2, DNC_TRACE_VARIABLE_ID_JACT, DNC_E_INVALID_AXIS,
    DNC32_E_LISTEN_FAIL, DNC_EVT_STATE_MACHINE_BOOTED, DNC_EC_NONE,
    DNC_DATA_UNIT_METER_PER_SEC, IJHDiagnostics, JHConfiguration,
    _midlSAFEARRAY, DNC_ACCESS_MODE_PLCDATAACCESS,
    IJHRemoteErrorEntryInternal, DNC_SW_TYPE_PLC, HRESULT,
    DNC_EC_NOTE, DNC32_E_NOT_CONN, DNC_E_CLIENT_REJECTED,
    DNC_TRIG_SEQUENCE_NONE, JHTraceVariableList, DNC_E_DIR_EXISTS,
    DNC_DATA_UNIT_MILLIMETER_PER_MINUTE, IUnknown, DNC_SW_TYPE_TNC_SG,
    JHDataEntry2Enum, DNC32_E_RESERVED, IJHTraceChannel,
    DNC_PLC_ACTION_WRITE, DNC_TRIG_ON_COND_LT, _DJHMachineEvents2,
    DNC_EG_OPERATING, IJHSecureConnectionHelper2,
    IJHSecureConnectionHelper3, DNC32_E_FAIL_WINSOCK,
    IJHDataAccessInternal, DNC_EG_PROGRAMING,
    DNC_DATA_UNIT_MILLIMETER_PER_SEC3, DNC32_E_RECV_FRAME,
    IJHErrorEntryList, IJHTraceSampleList, DNC_PROT_TCPIP,
    DNC_DATAENTRY_PROPKIND_SAMPLE_CAPABILITY,
    DNC_DATA_UNIT_DEGREE_PER_SEC3, DNC_SW_TYPE_MP_ADMS, DNC_PROT_DIO,
    DNC_TRACE_VARIABLE_ID_VNNOM, DNC_ACCESS_MODE_OEM,
    DNC_TRIG_ON_COND_NONE, JHPlcEvents, DNC_TRACE_VARIABLE_ID_VACT,
    TNCTable, DNC_TRACE_VARIABLE_ID_VNACT, DNC32_E_FAIL_SOCKET,
    JHAxisInfoEnum, DNC_ACCESS_MODE_NONE, IJHTraceChannelList,
    DNC_E_INVALID_DATA, DNC_ACCESS_MODE_DIAGNOSTICS,
    IJHDataEntryProperty2, DNC_E_HARD_DISK_FAIL,
    DNC_PRG_EVT_COMPLETED, JHPositioningResult, DNC_ACCESS_MODE_SYS,
    DNC_E_NOT_ADVISED, DNC_CNC_TYPE_TNC320_NCK,
    DNC_TRIG_ON_CHANGE_DELTA, DNC_TRACE_VARIABLE_ID_SACT,
    IJHProgramPositionList, JHFileSystemEvents, _IJHTestEvents,
    DNC_AXISTYPE_AUX_ROTARY, _IJHMachineEvents2Internal,
    DNC_E_WRONG_OPERATE_MODE, DNC_EXEC_SINGLESTEP,
    _DJHDiagnosticsEvents, DNC_E_MULTIPLE_OBJECTS, DNC32_E_PARITY,
    JHMachineInProcess, IJHCutterLocation, JHTestEvents, IJHError3,
    IJHDataEntryProperty, DNC_TRIG_ON_CHANGE, DNC_SW_TYPE_TNC_DSP1,
    _DJHAxesPositionStreamingEvents, JHMachineInProcessEvents2,
    DNC_STATE_HOST_IS_AVAILABLE, _DJHDataAccessEvents, Library,
    DNC_PLC_SIZE_WORD, DNC_E_NO_TRACE_DATA_AVAILABLE, _IJHPlcEvents,
    DNC_TRACE_VARIABLE_ID_NONE, DNC_PROT_LSV2, _DJHFileSystemEvents,
    IJHTraceInternal, IJHVersion, DNC_EC_INFO, DNC_CP_SPEED,
    IJHErrorInternal, DNC_E_FILE_OVERFLOW, DNC_CNC_TYPE_ITNC,
    DNC_ACCESS_MODE_GEODATAACCESS, DNC_STATE_WAITING_PERMISSION,
    DNC_E_PROGRAM_NOT_STARTED, DNC_DATA_UNIT_METER_PER_SEC4,
    DNC_DATA_UNIT_INCH_PER_MINUTE, JHCutterLocationList,
    DNC_PRG_EVT_FINISHED, DNC_TRACE_VARIABLE_TYPE_AXIS,
    DNC_TRACE_VARIABLE_TYPE_PATH, DNC_ACCESS_MODE_PLCDEBUG, BSTR,
    DNC_TRACE_VARIABLE_ID_BLOCK_NR, DNC_E_ITEM_DELETED,
    DNC_SW_TYPE_TNC_DSP3, DNC_ACCESS_MODE_SENDKEY,
    DNC_ERROR_LOCATION_NONE, DNC_SW_TYPE_TNC_DSP2, IJHCutterPosition,
    DNC_E_NO_PROGRAM, DNC_TRIG_ALWAYS, DNC_CNC_TYPE_TURNPLUS,
    DNC_PRG_EVT_SELECT_CLEARED, DNC_STATE_MACHINE_IS_AVAILABLE,
    DNC_INTERFACE_TNCTABLE, DNC_E_MISSING_PARAM,
    DNC_CP_SSH_IDENT_PASSWORD, DNC_TRACE_VARIABLE_ID_SDIFF,
    DNC_EG_PLC, DNC32_E_OPTION_VAL, JHTrigger,
    DNC_E_OPTION_NOT_AVAILABLE, DNC_E_FILE_EXISTS,
    JHProgramPositionList, DNC_DATA_UNIT_MILLIMETER,
    IJHFileAttributes, JHToolId, DNC_PRG_EVT_ERROR_CLEARED,
    DNC_SW_TYPE_UNKNOWN, DNC_INTERFACE_JHCONFIGURATION,
    DNC_E_COLLISION, DNC_CP_SSH_REMOTE_HOST_KEY_FINGERPRINT, JHPlc,
    DNC_E_NO_DRIVE_ACCESS, JHErrorEntry, IJHDataAccess3,
    DNC_MODE_REMOTE, DNC_CP_LSV_RX_TIMEOUT, IJHTraceVariableList,
    DNC32_E_STILL_CONN, DNC_EC_ERROR, DNC_AXISTYPE_AUX_LINEAR,
    JHFileSystem, DNC_E_FILE_REMOTE_FILENAME, DNC_DATA_UNIT_OTHER,
    JHSoftwareVersion, JHDirectoryEntryList, DNC_PLC_SIZE_BIT,
    DNC_ERROR_LOCATION_EDIT, DNC_E_RECORD_NOT_FOUND, DNC_CP_PORT,
    JHCutterLocation, DNC_SW_TYPE_FS_CCU, DNC_AXISTYPE_SPINDLE,
    JHTrace, DNC32_E_FAIL_CONNECT, DNC_TRIG_ON_COND_GT,
    DNC_STATE_DNC_IS_AVAILABLE, DNC_PRG_STS_FINISHED, IJHToolId,
    IJHChannelInfoList, IJHError, DNC_SW_TYPE_TNC_DSPSG2,
    DNC_TRACE_VARIABLE_ID_PLC, _check_version, DNC_EC_EMERGENCY_STOP,
    IJHTraceVariable, DNC_DATAENTRY_PROPKIND_DATAWIDTH,
    DNC_SPINDLE_STATE_CW, DNC_ATTRIBUTE_READONLY, IJHTrigger,
    DNC_EC_PROGRAMABORT, IJHTriggerCondition, _IJHDiagnosticsEvents,
    DNC32_E_VER_TOO_OLD, DNC_FILE_OBSERVE_REMOVE,
    IJHAxesPositionStreaming, JHRemoteErrorEvents,
    DNC_PROGRAMBREAKCONDITION_KIND_IGNORE_PROGRAMMED_STOP,
    JHAxisPositionEnum, DNC_E_IN_USE, DNC_STATE_HOST_IS_NOT_AVAILABLE,
    DNC_ATTRIBUTE_SYSTEM, IJHError2, DNC_TRIG_ON_COND_INSIDE,
    DNC_E_CANNOT_LOAD_PROGRAM, IJHAxisPosition,
    DNC_E_NO_PROGRAM_ACTIVE, DNC_DATAENTRY_PROPKIND_DATA, JHDataEntry,
    DNC_PRG_STS_RUNNING, _IJHErrorEvents, DNC_TRACE_VARIABLE_ID_CSI1,
    DNC32_E_INVALID_PARAM, DNC_E_ECLIPSED, DNC_DATA_UNIT_SECOND,
    IJHBreakConditionList, DNC_ATTRIBUTE_DIR, VARIANT_BOOL,
    IJHMachine2, DNC_INTERFACE_JHERROR, DNC_TRIG_ON_COND_EQ,
    DNC_ERROR_LOCATION_OEM, _IJHErrorEvents2,
    DNC_TRIG_INTERFACE_SAMPLING, DNC_SW_TYPE_TNC_DSPSG1,
    DNC_TRIG_SAMPLE_ON_PLC, DNC_SW_TYPE_TNC_ICTL2,
    DNC_PRG_STS_STOPPED, DNC_CNC_TYPE_CNCPILOT6xx_NCK,
    DNC32_E_FAIL_LOOKUP, IJHDataEntryProperty2List, DNC_EC_FEEDHOLD,
    DNC_CONFIGURE_MODE_ADD, IJHRemoteError, _DJHAutomaticEvents,
    DNC_DATAENTRY_PROPKIND_INITIALVALUE, DNC_ATTRIBUTE_HIDDEN,
    DNC_SW_TYPE_MC, DNC_DATA_UNIT_DEGREE_PER_SEC2,
    DNC_DATAENTRY_PROPKIND_UNITTEXT,
    DNC_DATA_UNIT_MILLIMETER_PER_SEC2, JHTraceSampleListList,
    DNC_CP_LSV_OPTIONS, DNC_POSSAMPLES_LOGGING_SAMPLED_WITH_AUX_AXES,
    DNC_POSSAMPLES_LOGGING_ENDPOINTS_WITH_AUX_AXES, DNC_E_FILE_IN_USE,
    JHRemoteErrorEntry, DNC_EG_NONE, JHTraceSampleList, DNC_PROT_COM,
    JHAxisPosition, DNC_EVT_STATE_DNC_AVAILABLE, IJHProgramPosition,
    JHDataAccess, DNC_EG_PYTHON, DNC_PRG_STS_IDLE,
    DNC_PLC_OPTION_NOSYNC, IJHConnectionProperty,
    IJHCutterLocation2List, DNC_ACCESS_MODE_TABLEDATAACCESS,
    DNC_TRACE_VARIABLE_ID_AACT, JHBreakConditionEnum,
    DNC_STATE_NOT_INITIALIZED, JHError, DNC32_E_TRANS_FAIL,
    DNC_INTERFACE_JHFILESYSTEM, DNC_PRG_EVT_STOPPED,
    DNC_SW_TYPE_TNC_MODEL, IJHConnection3, IJHProcessData,
    DNC_FILE_OBSERVE_REMOVE_ALL, IJHRemoteErrorInternal,
    DNC_AXISTYPE_MAIN_LINEAR, DNC_EVT_STATE_CONNECTION_LOST,
    DNC_TRACE_VARIABLE_ID_SERR, DNC_POSSAMPLES_MOTION_SPLINE,
    DNC_POSSAMPLES_LOGGING_SAMPLED_WITH_BLOCK_END_WITH_AUX_AXES,
    DNC_PROGRAMBREAKCONDITION_KIND_DEFAULT, DNC_E_READ_ONLY,
    DNC_CNC_TYPE_TNC6xx_NCK, JHDataEntryProperty, FEED_MODE_NORMAL,
    DNC_CP_LSV_AUTODETECT, DNC_SW_TYPE_TNC_DSPSG3,
    DNC_PROGRAMBREAKCONDITION_KIND_FORCE_OPTIONAL_STOP,
    JHCutterPosition, DNC_TRACE_VARIABLE_TYPE_UNKNOWN,
    DNC32_E_NO_ADDRESS, DNC_PROT_RPC_SECURE, JHDataEntry2List,
    JHDataEntryPropertyEnum, DNC_DATAENTRY_PROPKIND_UNIT,
    DNC_E_FILE_CANNOT_OPEN, DNC_E_NOT_POS_NOW, IJHFileSystem,
    DNC_TRIG_SAMPLE_ON_TIMER, IJHDataEntryPropertyList, ITNCTable,
    IJHConfiguration, DNC_E_LOCKED, FEED_MODE_RAPID,
    DNC_TRIG_ON_SUSTAINED_CONDITION, DNC_E_WRONG_MODE,
    DNC32_E_NOT_RES, _IJHDataAccessEvents2, IJHTriggerSampling,
    DNC_DATA_UNIT_DEGREE, DNC_AXISTYPE_MAIN_ROTARY, DNC_SW_TYPE_CC,
    DNC_STATE_MACHINE_IS_SHUTTING_DOWN, DNC_ACCESS_MODE_OEM_ENCRYPTED,
    JHCutterLocation2List, CoClass, _IJHFileSystemEvents,
    DNC_E_ITEM_NOT_FOUND, DNC_ACCESS_MODE_PLC, DNC_E_EXISTS,
    DNC_E_FILE_LOCKED, VARIANT, DNC_SPINDLE_STATE_RIGID_TAPPING,
    DNC_E_RPCFAILED, DNC_EXEC_RPF, DNC_TRACE_SOURCE_TYPE_PLC,
    JHAutomatic, DNC_STATE_NO_PERMISSION, DNC_TRACE_VARIABLE_ID_FEED,
    DNC_CNC_TYPE_ATEKM_NCK, DNC_E_SUBSCRIPTION_ACTIVE, IJHErrorEntry2,
    IJHDataEntryList, DNC_EVT_STATE_MACHINE_SHUTTING_DOWN,
    IJHAxisPositionListList, _DJHPlcEvents, DNC_E_NO_STREAMING_ACTIVE,
    IJHCutterLocationList, _IJHTraceEvents, IJHErrorEntry,
    DNC_ATTRIBUTE_MODIFIED, JHAxisPositionListEnum, helpstring,
    DNC_ACCESS_MODE_TESTUTILITY, DNC_ACCESS_MODE_ALL,
    DNC_TRIG_SEQUENCE_AND, IJHMachine4, DNC_E_SYNONYM_ACCESS,
    DNC_SPINDLE_STATE_STOPPED, DNC_TRIG_ON_COND_NEQ,
    DNC_E_TRACING_ACTIVE, JHProcessData, DNC_CNC_TYPE_MILLPLUSIT_NCK,
    DNC_E_ENDSWITCH_TRIPPED, _IJHAutomaticEvents,
    DNC_E_DIR_REMOTE_EXISTS, JHAxisInfo, DNC_EC_WARNING,
    DNC_PRG_EVT_ERROR, DNC_E_NOT_INITIALISED,
    DNC_SPINDLE_STATE_POS_CTRL, DNC_ERROR_LOCATION_MACHINE,
    DNC_PROGRAMBREAKCONDITION_KIND_ON_LINE, JHTraceChannelEnum,
    DNC_CNC_TYPE_MILLPLUS, DNC_E_DISK_FULL, DNC_PRG_EVT_INTERRUPTED,
    JHTraceSampleListEnum, _DJHErrorEvents,
    JHAxesPositionStreamingEvents, DNC_SW_TYPE_TNC_ICTL1,
    IJHPositioningResult, _DJHRemoteErrorEvents, JHDataEntryList,
    DNC_TRACE_VARIABLE_ID_ANALOG_OUT, DNC_TRIG_ON_COND_OUTSIDE,
    DNC32_E_RECV_FAIL, DNC_ACCESS_MODE_AXESPOSITIONSTREAMING,
    DNC32_E_CONNECT_LOST, DNC_CONFIGURE_MODE_REMOVE,
    DNC_CONFIGURE_MODE_ALL, DNC_EVT_STATE_HOST_NOT_AVAILABLE,
    JHTriggerEnum, DNC_DATA_UNIT_PER_MINUTE,
    IJHSecureConnectionHelper, IJHDataAccess4, DNC_CP_STOPBITS,
    DNC_E_FILE_REMOTE_NOT_FOUND, DNC_SW_TYPE_NCKERN,
    JHDataEntryPropertyList, DNC_E_REMOTE_READ_ONLY,
    JHAxisPositionList, JHTraceEvents, IJHTraceSampleListList,
    DNC_E_FILE_LOCAL_OPEN_FAILED, DNC32_E_INIT, DNC_DATA_UNIT_METER,
    IJHMachine, DNC_E_LOCAL_TO_UTC, JHCutterLocationEnum,
    DNC_POSSAMPLES_MOTION_COMPLEX, DNC_EG_GENERAL, IJHChannelInfo,
    JHAxesPositionStreaming, JHTriggerList, IJHDataEntry,
    DNC_E_OUT_OF_RANGE, DNC_INTERFACE_JHTRACE, DNC_E_DIR_OVERFLOW,
    JHTraceVariableEnum, JHTraceVariable, JHMachine,
    DNC_E_TRANSFER_ABORT, DNC_TRACE_SOURCE_TYPE_CCU,
    DNC_EVT_STATE_MACHINE_INITIALIZING, IJHDataEntry2List,
    DNC32_E_VER_TOO_NEW,
    DNC_POSSAMPLES_LOGGING_SAMPLED_WITH_BLOCK_END, IJHConnection2,
    DNC_E_KEY_UNDEFINED, JHDataEntryEnum, _lcid, DNC_PRG_EVT_STARTED,
    DNC_INTERFACE_JHPROCESSDATA, IJHTrace, DNC_EC_PROGRAMHOLD,
    JHBreakConditionList, JHDataEntryProperty2List,
    DNC_TRACE_VARIABLE_TYPE_NORMAL, DNC_ACCESS_MODE_IPODATAACCESS,
    IJHMachine3, DNC_DATAENTRY_PROPKIND_SUBSCRIBE_CAPABILITY,
    DNC_CNC_TYPE_ATEKM, DNC_SPINDLE_STATE_CCW, DNC_INTERFACE_JHPLC,
    DNC_EG_REMOTE, DNC_CP_SSH_REMOTE_USER, DNC_EXEC_AUTOMATIC,
    DNC_POSSAMPLES_MOTION_CIRCULAR, DNC_EC_RESET,
    DNC_TRACE_SOURCE_TYPE_IPO, JHDiagnosticsEvents,
    DNC_FILE_OBSERVE_ADD, DNC_E_HOST_REJECTED, JHChannelInfoEnum,
    IJHDataAccess, DNC_INTERFACE_JHAXESPOSITIONSTREAMING,
    DNC_E_UNABLE_TO_DELETE, JHCutterLocation2Enum, IJHTest,
    DNC_TRACE_VARIABLE_ID_ANOM, DNC_E_RECORD_LOCKED,
    DNC_DATA_UNIT_INCH, DNC_TRIG_MODE_NONE, DNC_ACCESS_MODE_DEFAULT,
    JHToolId0, DNC_E_FAIL, JHVirtualMachine, JHProgramPositionEnum,
    IJHAxisInfo, IJHCutterLocation2, DNC_ACCESS_MODE_INSPECT,
    IJHSoftwareVersionList, DNC32_E_FAIL_ACCEPT, typelib_path,
    DNC_CP_DIO_FLOWCTRL, DNC_INTERFACE_JHVERSION,
    DNC_TRIG_SAMPLE_ON_CCU, DNC_E_INVALID_PARAM, JHChannelInfoList,
    DNC_POSSAMPLES_LOGGING_ENDPOINTS, DNC_EVT_STATE_DNC_STOPPED,
    IJHTraceSample, JHDiagnostics, IJHConnectionList, DNC_CP_DATABITS,
    DNC32_E_RECV_TIMEOUT, DNC_PROT_TCPIP_SECURE,
    DNC_CNC_TYPE_GRINDPLUS_NCK, DNC_TRACE_VARIABLE_ID_CCDBG,
    DNC_DATA_UNIT_SELECT_INCH, DNC_DATA_UNIT_DEGREES_PER_MINUTE,
    JHErrorEntry2List, DNC_E_STREAMING_ACTIVE,
    DNC_INTERFACE_JHAUTOMATIC, DNC_E_NOT_LOCKED,
    DNC_INTERFACE_JHDIAGNOSTICS, JHDirectoryEntry, JHTraceChannelList,
    _IJHRemoteErrorEvents, IJHAutomatic,
    DNC_DATAENTRY_PROPKIND_DESCRIPTION, DNC_E_CANNOT_START_PROGRAM,
    JHProgramPosition, DNC_DATA_UNIT_DEGREE_PER_SEC4,
    DNC_ACCESS_MODE_DNC, _DJHTraceEvents, DNC_STATE_HOST_IS_STOPPED,
    DNC_EVT_STATE_PERMISSION_DENIED, DNC_CP_HOST,
    DNC_DATA_UNIT_METER_PER_SEC2, DNC_CP_PARITY,
    JHSoftwareVersionList, GUID, DNC_DATAENTRY_PROPKIND_LOCATION,
    DNC_TRACE_VARIABLE_ID_SNOM, DNC_PLC_SIZE_BYTE,
    DNC_E_FILE_NOT_FOUND, DNC_E_UNABLE_TO_SET, DNC_DATA_UNIT_VOLT,
    DNC_TRIG_SEQUENCE_OR, DNC_CP_CHECK_DTR, JHDataAccessEvents,
    DNC_MODE_LOCAL, JHChannelInfo, JHErrorEntry2Enum,
    DNC_ACCESS_MODE_MONITOR, DNC_TRACE_SOURCE_TYPE_UNKNOWN,
    JHAxisPositionListList, DNC_DATA_UNIT_DEGREE_PER_SEC,
    JHMachineEvents2, _IJHAutomaticEvents3, DNC_CP_LSV_RETRIES,
    JHSoftwareVersionEnum, DNC_E_DNC_PROHIBITED, DNC_E_UNABLE_TO_GET,
    DNC_E_TIMEOUT, DNC_E_LIST_EMPTY, DNC_DATA_UNIT_SELECT_METRIC,
    DNC_CONFIGURE_MODE_CHANGE, IJHErrorInternal2, DISPMETHOD,
    COMMETHOD, IJHErrorEntry2List, DNC_TRACE_VARIABLE_TYPE_CHANNEL,
    IJHBreakCondition, DNC_CP_DIO_PROTOCOL,
    DNC_TRACE_VARIABLE_ID_IPOLOGIC, IJHAxisInfoList,
    _IJHAutomaticEvents2, DNC_E_FILE_WRONG_MODE, IJHDataEntry2,
    DNC_STATE_DNC_IS_STOPPED, DNC_EXEC_SIMULO_TURBO_DEPRECATED,
    JHAxisInfoList, DNC_PLC_TYPE_MARKER, DNC_TRACE_VARIABLE_ID_CSI2,
    DNC32_E_NOT_PROT, DNC_INTERFACE_JHTEST,
    DNC_STATE_MACHINE_IS_BOOTED, DNC_DATAENTRY_PROPKIND_LOWER_BOUND,
    IJHSoftwareVersion, DNC_SW_TYPE_MP_UIMS, JHRemoteError,
    JHErrorEvents, JHErrorEntryList, DNC_E_FILE_OPEN_FAILED
)


class DNC_DATAENTRY_PROPKIND(IntFlag):
    DNC_DATAENTRY_PROPKIND_DATA = 0
    DNC_DATAENTRY_PROPKIND_UNIT = 1
    DNC_DATAENTRY_PROPKIND_UNITTEXT = 2
    DNC_DATAENTRY_PROPKIND_LOWER_BOUND = 3
    DNC_DATAENTRY_PROPKIND_UPPER_BOUND = 4
    DNC_DATAENTRY_PROPKIND_DESCRIPTION = 5
    DNC_DATAENTRY_PROPKIND_SUBSCRIBE_CAPABILITY = 6
    DNC_DATAENTRY_PROPKIND_SAMPLE_CAPABILITY = 7
    DNC_DATAENTRY_PROPKIND_DATAWIDTH = 8
    DNC_DATAENTRY_PROPKIND_INITIALVALUE = 9
    DNC_DATAENTRY_PROPKIND_LOCATION = 10
    DNC_DATAENTRY_PROPKIND_BASE_ENTRY = 11


class DNC_PLC_OPTION(IntFlag):
    DNC_PLC_OPTION_NOSYNC = 0


class DNC_STS_PROGRAM(IntFlag):
    DNC_PRG_STS_IDLE = 0
    DNC_PRG_STS_RUNNING = 1
    DNC_PRG_STS_STOPPED = 2
    DNC_PRG_STS_INTERRUPTED = 3
    DNC_PRG_STS_FINISHED = 4
    DNC_PRG_STS_ERROR = 5
    DNC_PRG_STS_NOT_SELECTED = 6


class DNC_CONNECTION_PROPERTY(IntFlag):
    DNC_CP_HOST = 0
    DNC_CP_PORT = 1
    DNC_CP_LSV_AUTODETECT = 2
    DNC_CP_SPEED = 3
    DNC_CP_DATABITS = 4
    DNC_CP_STOPBITS = 5
    DNC_CP_PARITY = 6
    DNC_CP_CHECK_DTR = 7
    DNC_CP_LSV_DELAY = 8
    DNC_CP_LSV_RETRIES = 9
    DNC_CP_LSV_OPTIONS = 10
    DNC_CP_LSV_TX_TIMEOUT = 11
    DNC_CP_LSV_RX_TIMEOUT = 12
    DNC_CP_DIO_PROTOCOL = 13
    DNC_CP_DIO_FLOWCTRL = 14
    DNC_CP_DIO_LEADERLENGTH = 15
    DNC_CP_SSH_IDENT = 16
    DNC_CP_SSH_IDENT_PASSWORD = 17
    DNC_CP_SSH_REMOTE_USER = 18
    DNC_CP_SSH_REMOTE_HOST_KEY_FINGERPRINT = 19


class DNC_PROTOCOL(IntFlag):
    DNC_PROT_DIO = 8
    DNC_PROT_LSV2 = 1
    DNC_PROT_TCPIP = 2
    DNC_PROT_COM = 4
    DNC_PROT_RPC = 5
    DNC_PROT_TCPIP_SECURE = 12
    DNC_PROT_RPC_SECURE = 15


class DNC_CNC_TYPE(IntFlag):
    DNC_CNC_TYPE_ATEKM = 0
    DNC_CNC_TYPE_ITNC = 1
    DNC_CNC_TYPE_MILLPLUS = 2
    DNC_CNC_TYPE_MILLPLUSIT = 3
    DNC_CNC_TYPE_TURNPLUS = 4
    DNC_CNC_TYPE_MILLPLUSIT_NCK = 5
    DNC_CNC_TYPE_MANUALPLUS_NCK = 6
    DNC_CNC_TYPE_ATEKM_NCK = 7
    DNC_CNC_TYPE_TNC320_NCK = 8
    DNC_CNC_TYPE_GRINDPLUS_NCK = 9
    DNC_CNC_TYPE_TNC6xx_NCK = 10
    DNC_CNC_TYPE_AR6000_NCK = 11
    DNC_CNC_TYPE_CNCPILOT6xx_NCK = 12
    DNC_CNC_TYPE_TNC128_NCK = 13
    DNC_CNC_TYPE_GRINDPLUS640_NCK = 14
    DNC_CNC_TYPE_TNC7_NCK = 15


class DNC_TRIG_SAMPLE_MODE(IntFlag):
    DNC_TRIG_SAMPLE_ON_CHANGE = 0
    DNC_TRIG_SAMPLE_ON_TIMER = 1
    DNC_TRIG_SAMPLE_ON_PLC = 2
    DNC_TRIG_SAMPLE_ON_IPO = 3
    DNC_TRIG_SAMPLE_ON_CCU = 4


class DNC_FEED_MODE(IntFlag):
    FEED_MODE_NORMAL = 0
    FEED_MODE_RAPID = 1


class DNC_SPINDLE_STATE(IntFlag):
    DNC_SPINDLE_STATE_CW = 0
    DNC_SPINDLE_STATE_CCW = 1
    DNC_SPINDLE_STATE_STOPPED = 2
    DNC_SPINDLE_STATE_POS_CTRL = 3
    DNC_SPINDLE_STATE_TAPPING = 4
    DNC_SPINDLE_STATE_RIGID_TAPPING = 5


class DNC_POSSAMPLES_MOTION_TYPE(IntFlag):
    DNC_POSSAMPLES_MOTION_COMPLEX = 0
    DNC_POSSAMPLES_MOTION_LINEAR = 1
    DNC_POSSAMPLES_MOTION_CIRCULAR = 2
    DNC_POSSAMPLES_MOTION_SPLINE = 3


class DNC_POSSAMPLES_LOGGING_TYPE(IntFlag):
    DNC_POSSAMPLES_LOGGING_SAMPLED = 0
    DNC_POSSAMPLES_LOGGING_ENDPOINTS = 1
    DNC_POSSAMPLES_LOGGING_SAMPLED_WITH_BLOCK_END = 2
    DNC_POSSAMPLES_LOGGING_NONLINEAR_SAMPLED_WITH_BLOCK_END = 3
    DNC_POSSAMPLES_LOGGING_SAMPLED_WITH_AUX_AXES = 4
    DNC_POSSAMPLES_LOGGING_ENDPOINTS_WITH_AUX_AXES = 5
    DNC_POSSAMPLES_LOGGING_SAMPLED_WITH_BLOCK_END_WITH_AUX_AXES = 6
    DNC_POSSAMPLES_LOGGING_NONLINEAR_SAMPLED_WITH_BLOCK_END_WITH_AUX_AXES = 7


class DNC_INTERFACE_OBJECT(IntFlag):
    DNC_INTERFACE_JHAUTOMATIC = 0
    DNC_INTERFACE_JHCONFIGURATION = 1
    DNC_INTERFACE_JHERROR = 2
    DNC_INTERFACE_JHPROCESSDATA = 3
    DNC_INTERFACE_JHVERSION = 4
    DNC_INTERFACE_JHFILESYSTEM = 5
    DNC_INTERFACE_JHPLC = 6
    DNC_INTERFACE_TNCTABLE = 7
    DNC_INTERFACE_JHAXESPOSITIONSTREAMING = 8
    DNC_INTERFACE_JHDATAACCESS = 9
    DNC_INTERFACE_JHTEST = 10
    DNC_INTERFACE_JHTRACE = 11
    DNC_INTERFACE_JHVIRTUALMACHINE = 12
    DNC_INTERFACE_JHDIAGNOSTICS = 13
    DNC_INTERFACE_JHREMOTEERROR = 14


class DNC_CONFIGURE_MODE(IntFlag):
    DNC_CONFIGURE_MODE_ADD = 0
    DNC_CONFIGURE_MODE_CHANGE = 1
    DNC_CONFIGURE_MODE_REMOVE = 2
    DNC_CONFIGURE_MODE_ALL = 3


class DNC_ERROR_GROUP(IntFlag):
    DNC_EG_NONE = 0
    DNC_EG_OPERATING = 1
    DNC_EG_PROGRAMING = 2
    DNC_EG_PLC = 3
    DNC_EG_GENERAL = 4
    DNC_EG_REMOTE = 5
    DNC_EG_PYTHON = 6


class DNC_ERROR_CLASS(IntFlag):
    DNC_EC_NONE = 0
    DNC_EC_WARNING = 1
    DNC_EC_FEEDHOLD = 2
    DNC_EC_PROGRAMHOLD = 3
    DNC_EC_PROGRAMABORT = 4
    DNC_EC_EMERGENCY_STOP = 5
    DNC_EC_RESET = 6
    DNC_EC_INFO = 7
    DNC_EC_ERROR = 8
    DNC_EC_NOTE = 9


class DNC_ERROR_LOCATION(IntFlag):
    DNC_ERROR_LOCATION_NONE = 0
    DNC_ERROR_LOCATION_MACHINE = 1
    DNC_ERROR_LOCATION_EDIT = 2
    DNC_ERROR_LOCATION_OEM = 3


class DNC_EVT_STATE(IntFlag):
    DNC_EVT_STATE_HOST_NOT_AVAILABLE = 0
    DNC_EVT_STATE_HOST_AVAILABLE = 1
    DNC_EVT_STATE_WAIT_PERMISSION = 2
    DNC_EVT_STATE_DNC_AVAILABLE = 3
    DNC_EVT_STATE_MACHINE_BOOTED = 4
    DNC_EVT_STATE_MACHINE_INITIALIZING = 5
    DNC_EVT_STATE_MACHINE_AVAILABLE = 6
    DNC_EVT_STATE_MACHINE_SHUTTING_DOWN = 7
    DNC_EVT_STATE_DNC_STOPPED = 8
    DNC_EVT_STATE_HOST_STOPPED = 9
    DNC_EVT_STATE_CONNECTION_LOST = 10
    DNC_EVT_STATE_PERMISSION_DENIED = 11


class DNC_TRIG_CONDITION(IntFlag):
    DNC_TRIG_ON_COND_NONE = 0
    DNC_TRIG_ON_COND_EQ = 1
    DNC_TRIG_ON_COND_NEQ = 2
    DNC_TRIG_ON_COND_LEQ = 3
    DNC_TRIG_ON_COND_GEQ = 4
    DNC_TRIG_ON_COND_LT = 5
    DNC_TRIG_ON_COND_GT = 6
    DNC_TRIG_ON_COND_INSIDE = 7
    DNC_TRIG_ON_COND_OUTSIDE = 8


class DNC_TRIG_MODE(IntFlag):
    DNC_TRIG_MODE_NONE = 0
    DNC_TRIG_ON_CHANGE = 1
    DNC_TRIG_ON_CHANGE_DELTA = 2
    DNC_TRIG_ON_RISE = 3
    DNC_TRIG_ON_FALL = 4
    DNC_TRIG_ON_CONDITION = 5
    DNC_TRIG_ON_SUSTAINED_CONDITION = 6
    DNC_TRIG_ALWAYS = 7


class DNC_STATE(IntFlag):
    DNC_STATE_NOT_INITIALIZED = 0
    DNC_STATE_HOST_IS_NOT_AVAILABLE = 1
    DNC_STATE_HOST_IS_AVAILABLE = 2
    DNC_STATE_WAITING_PERMISSION = 3
    DNC_STATE_DNC_IS_AVAILABLE = 4
    DNC_STATE_MACHINE_IS_BOOTED = 5
    DNC_STATE_MACHINE_IS_INITIALIZING = 6
    DNC_STATE_MACHINE_IS_AVAILABLE = 7
    DNC_STATE_MACHINE_IS_SHUTTING_DOWN = 8
    DNC_STATE_DNC_IS_STOPPED = 9
    DNC_STATE_HOST_IS_STOPPED = 10
    DNC_STATE_NO_PERMISSION = 11


class DNC_ACCESS_MODE(IntFlag):
    DNC_ACCESS_MODE_DEFAULT = 0
    DNC_ACCESS_MODE_USR_PRIVATE = 1
    DNC_ACCESS_MODE_OEM = 2
    DNC_ACCESS_MODE_SYS = 3
    DNC_ACCESS_MODE_INSPECT = 4
    DNC_ACCESS_MODE_DIAGNOSTICS = 5
    DNC_ACCESS_MODE_PLCDEBUG = 6
    DNC_ACCESS_MODE_USR = 7
    DNC_ACCESS_MODE_MONITOR = 8
    DNC_ACCESS_MODE_DSP = 9
    DNC_ACCESS_MODE_DNC = 10
    DNC_ACCESS_MODE_SCOPE = 11
    DNC_ACCESS_MODE_ALL = 12
    DNC_ACCESS_MODE_AUTOMATIC = 13
    DNC_ACCESS_MODE_PLC = 14
    DNC_ACCESS_MODE_IPODATAACCESS = 15
    DNC_ACCESS_MODE_OEM_ENCRYPTED = 16
    DNC_ACCESS_MODE_NONE = 17
    DNC_ACCESS_MODE_TESTUTILITY = 18
    DNC_ACCESS_MODE_SENDKEY = 19
    DNC_ACCESS_MODE_AXESPOSITIONSTREAMING = 20
    DNC_ACCESS_MODE_SPLCDATAACCESS = 21
    DNC_ACCESS_MODE_HWSDATAACCESS = 22
    DNC_ACCESS_MODE_TABLEDATAACCESS = 23
    DNC_ACCESS_MODE_PLCDATAACCESS = 24
    DNC_ACCESS_MODE_GEODATAACCESS = 25
    DNC_ACCESS_MODE_CFGDATAACCESS = 26
    DNC_ACCESS_MODE_GEOSIMDATAACCESS = 27


class DNC_KEYACTION(IntFlag):
    DNC_KEYACTION_DOWN_UP = 0
    DNC_KEYACTION_DOWN = 1
    DNC_KEYACTION_UP = 2


class DNC_TRACE_VARIABLE_ID(IntFlag):
    DNC_TRACE_VARIABLE_ID_NONE = 0
    DNC_TRACE_VARIABLE_ID_AACT = 1
    DNC_TRACE_VARIABLE_ID_ANOM = 2
    DNC_TRACE_VARIABLE_ID_VACT = 3
    DNC_TRACE_VARIABLE_ID_VNOM = 4
    DNC_TRACE_VARIABLE_ID_FEED = 5
    DNC_TRACE_VARIABLE_ID_BLOCK_NR = 6
    DNC_TRACE_VARIABLE_ID_SACT = 7
    DNC_TRACE_VARIABLE_ID_SNOM = 8
    DNC_TRACE_VARIABLE_ID_SERR = 9
    DNC_TRACE_VARIABLE_ID_SDIFF = 10
    DNC_TRACE_VARIABLE_ID_CSI1 = 11
    DNC_TRACE_VARIABLE_ID_CSI2 = 12
    DNC_TRACE_VARIABLE_ID_JACT = 13
    DNC_TRACE_VARIABLE_ID_JNOM = 14
    DNC_TRACE_VARIABLE_ID_VNACT = 15
    DNC_TRACE_VARIABLE_ID_VNNOM = 16
    DNC_TRACE_VARIABLE_ID_ININT = 17
    DNC_TRACE_VARIABLE_ID_INOM = 18
    DNC_TRACE_VARIABLE_ID_PLC = 19
    DNC_TRACE_VARIABLE_ID_ANALOG_OUT = 20
    DNC_TRACE_VARIABLE_ID_IPODBG = 21
    DNC_TRACE_VARIABLE_ID_CCDBG = 22
    DNC_TRACE_VARIABLE_ID_IPOLOGIC = 23


class DNC_TRACE_VARIABLE_TYPE(IntFlag):
    DNC_TRACE_VARIABLE_TYPE_UNKNOWN = 0
    DNC_TRACE_VARIABLE_TYPE_NORMAL = 1
    DNC_TRACE_VARIABLE_TYPE_AXIS = 2
    DNC_TRACE_VARIABLE_TYPE_CHANNEL = 3
    DNC_TRACE_VARIABLE_TYPE_PATH = 4


class DNC_PLC_ACTION(IntFlag):
    DNC_PLC_ACTION_WRITE = 8192


class DNC_TRACE_SOURCE_TYPE(IntFlag):
    DNC_TRACE_SOURCE_TYPE_UNKNOWN = 0
    DNC_TRACE_SOURCE_TYPE_IPO = 1
    DNC_TRACE_SOURCE_TYPE_CCU = 2
    DNC_TRACE_SOURCE_TYPE_PLC = 3


class DNC_HRESULT(IntFlag):
    DNC_E_FAIL = -2147220991
    DNC_E_ALL_CONNECTIONS_IN_USE = -2147220896
    DNC_E_OPTION_NOT_AVAILABLE = -2147220895
    DNC_E_DNC32FAILED = -2147220894
    DNC_E_RPCFAILED = -2147220893
    DNC_E_INVALID_PARAM = -2147220892
    DNC_E_WRONG_MODE = -2147220891
    DNC_E_NOT_POS_NOW = -2147220890
    DNC_E_WRONG_OPERATE_MODE = -2147220889
    DNC_E_OUT_OF_RANGE = -2147220888
    DNC_E_NOT_INITIALISED = -2147220887
    DNC_E_DNC_PROHIBITED = -2147220886
    DNC_E_TOO_MANY_ELEMENTS = -2147220885
    DNC_E_LIST_EMPTY = -2147220884
    DNC_E_READ_ONLY = -2147220883
    DNC_E_INVALID_DATA = -2147220882
    DNC_E_NOT_ADVISED = -2147220881
    DNC_E_MULTIPLE_OBJECTS = -2147220880
    DNC_E_TRANSFER_ABORT = -2147220879
    DNC_E_INVALID_PASSWORD = -2147220878
    DNC_E_CANNOT_RESTORE_DEFAULT = -2147220877
    DNC_E_MISSING_PARAM = -2147220876
    DNC_E_UNABLE_TO_GET = -2147220875
    DNC_E_UNABLE_TO_SET = -2147220874
    DNC_E_UTC_TO_LOCAL = -2147220873
    DNC_E_LOCAL_TO_UTC = -2147220872
    DNC_E_STREAMING_ACTIVE = -2147220871
    DNC_E_NO_STREAMING_ACTIVE = -2147220870
    DNC_E_INVALID_AXIS = -2147220869
    DNC_E_ITEM_NOT_FOUND = -2147220868
    DNC_E_EXISTS = -2147220867
    DNC_E_INVALID_CHANNEL = -2147220866
    DNC_E_SUBSCRIPTION_ACTIVE = -2147220865
    DNC_E_ITEM_DELETED = -2147220864
    DNC_E_IN_USE = -2147220863
    DNC_E_TIMEOUT = -2147220862
    DNC_E_ECLIPSED = -2147220861
    DNC_E_RECORD_NOT_FOUND = -2147220792
    DNC_E_UNABLE_TO_INSERT = -2147220791
    DNC_E_UNABLE_TO_DELETE = -2147220790
    DNC_E_RECORD_LOCKED = -2147220789
    DNC_E_SYNONYM_ACCESS = -2147220788
    DNC_E_KEY_UNDEFINED = -2147220787
    DNC_E_LOCKED = -2147220786
    DNC_E_NOT_LOCKED = -2147220785
    DNC_E_TRACING_ACTIVE = -2147220692
    DNC_E_NO_TRACING_ACTIVE = -2147220691
    DNC_E_NO_TRACE_DATA_AVAILABLE = -2147220690
    DNC_E_NO_PROGRAM = -2147220391
    DNC_E_PROGRAM_NOT_STARTED = -2147220390
    DNC_E_NO_PROGRAM_ACTIVE = -2147220389
    DNC_E_CANNOT_START_PROGRAM = -2147220388
    DNC_E_CANNOT_LOAD_PROGRAM = -2147220387
    DNC_E_ENDSWITCH_TRIPPED = -2147220386
    DNC_E_COLLISION = -2147220385
    DNC_E_HARD_DISK_FAIL = -2147220291
    DNC_E_DISK_FULL = -2147220290
    DNC_E_NO_DRIVE_ACCESS = -2147220289
    DNC_E_DIR_NOT_EMPTY = -2147220288
    DNC_E_DIR_EXISTS = -2147220287
    DNC_E_DIR_NESTING = -2147220286
    DNC_E_DIR_OVERFLOW = -2147220285
    DNC_E_DIR_NOT_FOUND = -2147220284
    DNC_E_FILE_EXISTS = -2147220283
    DNC_E_FILE_LOCKED = -2147220282
    DNC_E_FILE_FILENAME = -2147220281
    DNC_E_FILE_NOT_FOUND = -2147220280
    DNC_E_FILE_IN_USE = -2147220279
    DNC_E_FILE_OVERFLOW = -2147220278
    DNC_E_FILE_OPEN_FAILED = -2147220277
    DNC_E_FILE_WRONG_MODE = -2147220276
    DNC_E_DIR_LOCKED = -2147220275
    DNC_E_FILE_REMOTE_NOT_FOUND = -2147220274
    DNC_E_FILE_REMOTE_EXISTS = -2147220273
    DNC_E_FILE_REMOTE_LOCKED = -2147220272
    DNC_E_FILE_REMOTE_FILENAME = -2147220271
    DNC_E_DIR_REMOTE_NOT_FOUND = -2147220270
    DNC_E_DIR_REMOTE_LOCKED = -2147220269
    DNC_E_DIR_REMOTE_EXISTS = -2147220268
    DNC_E_REMOTE_READ_ONLY = -2147220267
    DNC_E_FILE_LOCAL_OPEN_FAILED = -2147220266
    DNC_E_FILE_CANNOT_OPEN = -2147220264
    DNC32_E_STILL_CONN = -2147219791
    DNC32_E_NOT_CONN = -2147219790
    DNC32_E_NOT_HANDLE = -2147219789
    DNC32_E_FAIL_HANDLE = -2147219788
    DNC32_E_INIT = -2147219787
    DNC32_E_NOT_PROT = -2147219786
    DNC32_E_TRANS_FAIL = -2147219785
    DNC32_E_RECV_FAIL = -2147219784
    DNC32_E_RESERVED = -2147219783
    DNC32_E_NOT_RES = -2147219782
    DNC32_E_RECV_FRAME = -2147219781
    DNC32_E_RECV_TIMEOUT = -2147219780
    DNC32_E_VER_TOO_OLD = -2147219779
    DNC32_E_VER_TOO_NEW = -2147219778
    DNC32_E_TIMEOUT_VAL = -2147219777
    DNC32_E_OPTION_VAL = -2147219776
    DNC32_E_NO_ADDRESS = -2147219775
    DNC32_E_NO_PORT = -2147219774
    DNC32_E_PARITY = -2147219773
    DNC32_E_FAIL_WINSOCK = -2147219772
    DNC32_E_FAIL_LOOKUP = -2147219771
    DNC32_E_FAIL_SOCKET = -2147219770
    DNC32_E_FAIL_CONNECT = -2147219769
    DNC32_E_FAIL_ACCEPT = -2147219768
    DNC32_E_INVALID_PARAM = -2147219767
    DNC32_E_NO_AUTODETECT = -2147219766
    DNC32_E_LISTEN_FAIL = -2147219765
    DNC32_E_CONNECT_LOST = -2147219764
    DNC_E_HOST_REJECTED = -2147219763
    DNC_E_CLIENT_REJECTED = -2147219762


class DNC_DATA_UNIT_SELECT(IntFlag):
    DNC_DATA_UNIT_SELECT_INCH = 0
    DNC_DATA_UNIT_SELECT_METRIC = 1


class DNC_MODE(IntFlag):
    DNC_MODE_LOCAL = 0
    DNC_MODE_REMOTE = 1


class DNC_EXEC_MODE(IntFlag):
    DNC_EXEC_MANUAL = 0
    DNC_EXEC_MDI = 1
    DNC_EXEC_RPF = 2
    DNC_EXEC_SINGLESTEP = 3
    DNC_EXEC_AUTOMATIC = 4
    DNC_EXEC_OTHER = 5
    DNC_EXEC_SIMULO_TURBO_DEPRECATED = 6
    DNC_EXEC_HANDWHEEL = 7


class DNC_DATA_UNIT(IntFlag):
    DNC_DATA_UNIT_NONE = 0
    DNC_DATA_UNIT_OTHER = 1
    DNC_DATA_UNIT_SECOND = 2
    DNC_DATA_UNIT_METER = 3
    DNC_DATA_UNIT_METER_PER_SEC = 4
    DNC_DATA_UNIT_METER_PER_SEC2 = 5
    DNC_DATA_UNIT_METER_PER_SEC3 = 6
    DNC_DATA_UNIT_METER_PER_SEC4 = 7
    DNC_DATA_UNIT_DEGREE = 8
    DNC_DATA_UNIT_DEGREE_PER_SEC = 9
    DNC_DATA_UNIT_DEGREE_PER_SEC2 = 10
    DNC_DATA_UNIT_DEGREE_PER_SEC3 = 11
    DNC_DATA_UNIT_DEGREE_PER_SEC4 = 12
    DNC_DATA_UNIT_PER_MINUTE = 13
    DNC_DATA_UNIT_MILLIMETER = 14
    DNC_DATA_UNIT_MILLIMETER_PER_MINUTE = 15
    DNC_DATA_UNIT_MILLIMETER_PER_SEC2 = 16
    DNC_DATA_UNIT_MILLIMETER_PER_SEC3 = 17
    DNC_DATA_UNIT_INCH = 18
    DNC_DATA_UNIT_INCH_PER_MINUTE = 19
    DNC_DATA_UNIT_DEGREES_PER_MINUTE = 20
    DNC_DATA_UNIT_VOLT = 21
    DNC_DATA_UNIT_AMPERE = 22


class DNC_EVT_PROGRAM(IntFlag):
    DNC_PRG_EVT_STARTED = 0
    DNC_PRG_EVT_STOPPED = 1
    DNC_PRG_EVT_FINISHED = 2
    DNC_PRG_EVT_CANCELED = 3
    DNC_PRG_EVT_INTERRUPTED = 4
    DNC_PRG_EVT_COMPLETED = 5
    DNC_PRG_EVT_ERROR = 6
    DNC_PRG_EVT_ERROR_CLEARED = 7
    DNC_PRG_EVT_SELECTED = 8
    DNC_PRG_EVT_SELECT_CLEARED = 9


class DNC_TRIG_INTERFACE(IntFlag):
    DNC_TRIG_INTERFACE_CONDITION = 0
    DNC_TRIG_INTERFACE_SAMPLING = 1


class DNC_TRIG_SEQUENCE(IntFlag):
    DNC_TRIG_SEQUENCE_NONE = 0
    DNC_TRIG_SEQUENCE_AND = 1
    DNC_TRIG_SEQUENCE_OR = 2
    DNC_TRIG_SEQUENCE_AND_THEN = 3


class DNC_SW_TYPE(IntFlag):
    DNC_SW_TYPE_MC = 0
    DNC_SW_TYPE_CC = 1
    DNC_SW_TYPE_PLC = 2
    DNC_SW_TYPE_MP_UIMS = 3
    DNC_SW_TYPE_MP_ADMS = 4
    DNC_SW_TYPE_TNC_MODEL = 5
    DNC_SW_TYPE_TNC_SG = 6
    DNC_SW_TYPE_TNC_DSP1 = 7
    DNC_SW_TYPE_TNC_DSP2 = 8
    DNC_SW_TYPE_TNC_DSP3 = 9
    DNC_SW_TYPE_TNC_DSPSG1 = 10
    DNC_SW_TYPE_TNC_DSPSG2 = 11
    DNC_SW_TYPE_TNC_DSPSG3 = 12
    DNC_SW_TYPE_TNC_ICTL1 = 13
    DNC_SW_TYPE_TNC_ICTL2 = 14
    DNC_SW_TYPE_TNC_ICTL3 = 15
    DNC_SW_TYPE_TNC_OPT = 16
    DNC_SW_TYPE_TNC_OTHER = 17
    DNC_SW_TYPE_UNKNOWN = 18
    DNC_SW_TYPE_NCKERN = 19
    DNC_SW_TYPE_FCL = 20
    DNC_SW_TYPE_SPLC = 21
    DNC_SW_TYPE_FS_MCU = 22
    DNC_SW_TYPE_FS_CCU = 23


class DNC_FILE_OBSERVE(IntFlag):
    DNC_FILE_OBSERVE_ADD = 0
    DNC_FILE_OBSERVE_REMOVE = 1
    DNC_FILE_OBSERVE_REMOVE_ALL = 2


class DNC_ATTRIBUTE_TYPE(IntFlag):
    DNC_ATTRIBUTE_READONLY = 0
    DNC_ATTRIBUTE_HIDDEN = 1
    DNC_ATTRIBUTE_DIR = 2
    DNC_ATTRIBUTE_SYSTEM = 3
    DNC_ATTRIBUTE_MODIFIED = 4
    DNC_ATTRIBUTE_LOCKED = 5


class DNC_PROGRAMBREAKCONDITION_KIND(IntFlag):
    DNC_PROGRAMBREAKCONDITION_KIND_DEFAULT = 0
    DNC_PROGRAMBREAKCONDITION_KIND_FORCE_OPTIONAL_STOP = 1
    DNC_PROGRAMBREAKCONDITION_KIND_IGNORE_PROGRAMMED_STOP = 2
    DNC_PROGRAMBREAKCONDITION_KIND_ON_LINE = 3


class DNC_AXISTYPE(IntFlag):
    DNC_AXISTYPE_MAIN_LINEAR = 0
    DNC_AXISTYPE_MAIN_ROTARY = 1
    DNC_AXISTYPE_AUX_LINEAR = 2
    DNC_AXISTYPE_AUX_ROTARY = 3
    DNC_AXISTYPE_SPINDLE = 4


class DNC_PLC_SIZE(IntFlag):
    DNC_PLC_SIZE_BIT = 256
    DNC_PLC_SIZE_BYTE = 512
    DNC_PLC_SIZE_WORD = 1024


class DNC_PLC_TYPE(IntFlag):
    DNC_PLC_TYPE_MARKER = 1


__all__ = [
    'DNC_EXEC_MDI', 'DNC_CP_DIO_LEADERLENGTH',
    'DNC_E_INVALID_PASSWORD', 'DNC_CP_SSH_IDENT',
    'DNC_ACCESS_MODE_USR', 'DNC_TRIG_ON_CONDITION',
    'DNC_CNC_TYPE_TNC128_NCK', '_IJHDataAccessEvents',
    'DNC_KEYACTION_DOWN', 'DNC_DATA_UNIT_AMPERE', 'IJHVirtualMachine',
    'DNC_EVT_STATE_HOST_STOPPED', 'JHTest',
    'DNC_POSSAMPLES_LOGGING_NONLINEAR_SAMPLED_WITH_BLOCK_END',
    'DNC_CNC_TYPE_AR6000_NCK', 'DNC_TRIG_SAMPLE_ON_CHANGE',
    '_DJHTestEvents', 'JHTraceSampleEnum', 'DNC_PRG_EVT_SELECTED',
    'DNC_CP_LSV_DELAY', 'DNC_ACCESS_MODE_SCOPE',
    'DNC_PRG_STS_INTERRUPTED', 'DNC_INTERFACE_JHDATAACCESS',
    'JHDirectoryEntryEnum', 'DNC_TRACE_VARIABLE_ID_VNOM',
    'JHErrorEntryEnum', 'IJHAxisPositionList',
    'DNC_SPINDLE_STATE_TAPPING', 'DNC_INTERFACE_JHVIRTUALMACHINE',
    'DNC_E_DIR_NOT_FOUND', 'DNC_CNC_TYPE_MANUALPLUS_NCK',
    'DNC_TRACE_VARIABLE_ID_JNOM', 'DNC_CONNECTION_PROPERTY',
    'DNC_E_DIR_REMOTE_LOCKED', 'DNC_ACCESS_MODE_AUTOMATIC',
    'IJHAutomatic4', 'JHVersion', 'DNC_EXEC_OTHER',
    'DNC32_E_FAIL_HANDLE', 'DNC32_E_NO_AUTODETECT',
    'DNC_TRIG_SEQUENCE_AND_THEN', 'DNC_SW_TYPE_TNC_OTHER',
    'DNC_ATTRIBUTE_TYPE', 'DNC_STATE_MACHINE_IS_INITIALIZING',
    'JHFileAttributes', 'IEventObject', 'DNC_TRIG_SAMPLE_ON_IPO',
    'DNC_SW_TYPE_FS_MCU', 'DNC_E_DIR_NOT_EMPTY', 'DNC_E_DIR_NESTING',
    'DNC_KEYACTION_DOWN_UP', 'DNC_EVT_STATE_HOST_AVAILABLE',
    'IJHRemoteErrorEntry', 'DNC_ATTRIBUTE_LOCKED',
    'DNC_POSSAMPLES_LOGGING_NONLINEAR_SAMPLED_WITH_BLOCK_END_WITH_AUX_AXES',
    'DNC_INTERFACE_JHREMOTEERROR',
    'DNC_DATAENTRY_PROPKIND_UPPER_BOUND',
    'DNC_CNC_TYPE_GRINDPLUS640_NCK', 'IJHAxesPositionStreaming2',
    'DNC_PRG_STS_NOT_SELECTED', '_IJHMachineEvents2',
    'JHTraceChannel', 'DNC_ERROR_CLASS', 'IJHAutomatic2',
    'IJHLoggingInternal', 'IJHConnection',
    'DNC_DATAENTRY_PROPKIND_BASE_ENTRY',
    'DNC_EVT_STATE_MACHINE_AVAILABLE', 'DNC_SW_TYPE_TNC_OPT',
    'DNC_ACCESS_MODE_HWSDATAACCESS', 'DNC_TRIG_ON_RISE',
    '_IJHAxesPositionStreamingEvents', 'JHTraceSample',
    'DNC_ACCESS_MODE_DSP', 'DNC_TRIG_ON_COND_LEQ',
    'DNC_DATA_UNIT_METER_PER_SEC3', 'DNC_E_FILE_REMOTE_LOCKED',
    'DNC_POSSAMPLES_MOTION_LINEAR', 'IJHTriggerList', 'IJHAutomatic3',
    'DNC_CP_LSV_TX_TIMEOUT', 'DNC_ACCESS_MODE_USR_PRIVATE',
    'DNC_DATA_UNIT', 'DNC_SW_TYPE_SPLC', 'JHBreakCondition',
    'DNC_E_FILE_FILENAME', 'DNC_PRG_EVT_CANCELED',
    'DNC32_E_NOT_HANDLE', 'DNC_E_UTC_TO_LOCAL',
    'DNC_E_NO_TRACING_ACTIVE', 'DNC_HANDLE',
    'DNC_E_CANNOT_RESTORE_DEFAULT', 'DNC_E_UNABLE_TO_INSERT',
    'DNC32_E_TIMEOUT_VAL', 'DNC_EXEC_HANDWHEEL',
    'DNC_POSSAMPLES_LOGGING_SAMPLED', 'DNC_ACCESS_MODE_CFGDATAACCESS',
    'DNC_ACCESS_MODE_GEOSIMDATAACCESS', 'DNC_SW_TYPE_FCL',
    'DNC_TRIG_ON_COND_GEQ', 'DNC_E_DIR_REMOTE_NOT_FOUND',
    'DNC_PROT_RPC', 'DNC_TRIG_ON_FALL', 'DNC_PRG_STS_ERROR',
    'DNC_TRACE_VARIABLE_ID_IPODBG', 'DNC_CNC_TYPE_MILLPLUSIT',
    'DNC_KEYACTION_UP', 'DNC_E_INVALID_CHANNEL', 'DNC32_E_NO_PORT',
    'JHDataEntryProperty2Enum', 'DNC_DATA_UNIT_NONE',
    'DNC_E_DIR_LOCKED', 'DNC_TRACE_VARIABLE_ID_ININT',
    'DNC_ACCESS_MODE_SPLCDATAACCESS', 'DNC_E_DNC32FAILED', 'IJHPlc',
    'DNC_TRACE_VARIABLE_ID_INOM', 'DNC_E_FILE_REMOTE_EXISTS',
    'JHAutomaticEvents', 'DNC_EXEC_MANUAL', 'DNC_CNC_TYPE_TNC7_NCK',
    'DNC_TRIG_INTERFACE_CONDITION', 'DNC_EVT_STATE_WAIT_PERMISSION',
    'IJHDirectoryEntryList', 'DNC_E_ALL_CONNECTIONS_IN_USE',
    'DNC_E_TOO_MANY_ELEMENTS', 'IJHDirectoryEntry',
    'DNC_SW_TYPE_TNC_ICTL3', 'DNC_POSSAMPLES_LOGGING_TYPE',
    'IJHDataAccess2', 'DNC_TRACE_VARIABLE_ID_JACT',
    'DNC_E_INVALID_AXIS', 'DNC_TRACE_VARIABLE_ID', 'DNC_EXEC_MODE',
    'DNC32_E_LISTEN_FAIL', 'DNC_EVT_STATE_MACHINE_BOOTED',
    'DNC_EC_NONE', 'DNC_DATA_UNIT_METER_PER_SEC', 'IJHDiagnostics',
    'JHConfiguration', 'DNC_ACCESS_MODE_PLCDATAACCESS',
    'IJHRemoteErrorEntryInternal', 'DNC_SW_TYPE_PLC', 'DNC_EC_NOTE',
    'DNC32_E_NOT_CONN', 'DNC_E_CLIENT_REJECTED',
    'DNC_TRIG_SEQUENCE_NONE', 'JHTraceVariableList',
    'DNC_E_DIR_EXISTS', 'DNC_DATA_UNIT_MILLIMETER_PER_MINUTE',
    'DNC_SW_TYPE_TNC_SG', 'JHDataEntry2Enum', 'DNC32_E_RESERVED',
    'IJHTraceChannel', 'DNC_PLC_ACTION_WRITE', 'DNC_TRIG_ON_COND_LT',
    'DNC_STS_PROGRAM', '_DJHMachineEvents2', 'DNC_EG_OPERATING',
    'IJHSecureConnectionHelper2', 'IJHSecureConnectionHelper3',
    'DNC_ERROR_LOCATION', 'DNC32_E_FAIL_WINSOCK',
    'IJHDataAccessInternal', 'DNC_EG_PROGRAMING', 'DNC_EVT_STATE',
    'DNC_DATA_UNIT_MILLIMETER_PER_SEC3', 'DNC32_E_RECV_FRAME',
    'IJHErrorEntryList', 'IJHTraceSampleList', 'DNC_PROT_TCPIP',
    'DNC_DATAENTRY_PROPKIND_SAMPLE_CAPABILITY',
    'DNC_DATA_UNIT_DEGREE_PER_SEC3', 'DNC_SW_TYPE_MP_ADMS',
    'DNC_PROT_DIO', 'DNC_TRACE_VARIABLE_ID_VNNOM',
    'DNC_ACCESS_MODE_OEM', 'DNC_TRIG_ON_COND_NONE', 'JHPlcEvents',
    'DNC_TRACE_VARIABLE_ID_VACT', 'TNCTable',
    'DNC_TRACE_VARIABLE_ID_VNACT', 'DNC32_E_FAIL_SOCKET',
    'JHAxisInfoEnum', 'DNC_ACCESS_MODE_NONE', 'IJHTraceChannelList',
    'DNC_E_INVALID_DATA', 'DNC_ACCESS_MODE_DIAGNOSTICS',
    'IJHDataEntryProperty2', 'DNC_E_HARD_DISK_FAIL',
    'DNC_PRG_EVT_COMPLETED', 'JHPositioningResult',
    'DNC_ACCESS_MODE_SYS', 'DNC_SW_TYPE', 'DNC_E_NOT_ADVISED',
    'DNC_CNC_TYPE_TNC320_NCK', 'DNC_TRIG_ON_CHANGE_DELTA',
    'DNC_TRACE_VARIABLE_ID_SACT', 'IJHProgramPositionList',
    'JHFileSystemEvents', '_IJHTestEvents', 'DNC_AXISTYPE_AUX_ROTARY',
    '_IJHMachineEvents2Internal', 'DNC_E_WRONG_OPERATE_MODE',
    'DNC_EXEC_SINGLESTEP', '_DJHDiagnosticsEvents', 'DNC_HRESULT',
    'DNC_E_MULTIPLE_OBJECTS', 'DNC32_E_PARITY', 'JHMachineInProcess',
    'DNC_CNC_TYPE', 'IJHCutterLocation', 'DNC_PROTOCOL',
    'JHTestEvents', 'IJHError3', 'IJHDataEntryProperty',
    'DNC_TRIG_ON_CHANGE', 'DNC_SW_TYPE_TNC_DSP1',
    '_DJHAxesPositionStreamingEvents', 'JHMachineInProcessEvents2',
    'DNC_STATE_HOST_IS_AVAILABLE', '_DJHDataAccessEvents', 'Library',
    'DNC_PLC_SIZE_WORD', 'DNC_E_NO_TRACE_DATA_AVAILABLE',
    '_IJHPlcEvents', 'DNC_TRACE_VARIABLE_ID_NONE', 'DNC_PROT_LSV2',
    '_DJHFileSystemEvents', 'IJHTraceInternal', 'IJHVersion',
    'DNC_EC_INFO', 'DNC_CP_SPEED', 'IJHErrorInternal',
    'DNC_E_FILE_OVERFLOW', 'DNC_CNC_TYPE_ITNC',
    'DNC_ACCESS_MODE_GEODATAACCESS', 'DNC_STATE_WAITING_PERMISSION',
    'DNC_E_PROGRAM_NOT_STARTED', 'DNC_DATA_UNIT_METER_PER_SEC4',
    'DNC_DATA_UNIT_INCH_PER_MINUTE', 'JHCutterLocationList',
    'DNC_PRG_EVT_FINISHED', 'DNC_TRACE_VARIABLE_TYPE_AXIS',
    'DNC_TRACE_VARIABLE_TYPE_PATH', 'DNC_ACCESS_MODE_PLCDEBUG',
    'DNC_TRACE_VARIABLE_ID_BLOCK_NR', 'DNC_E_ITEM_DELETED',
    'DNC_SW_TYPE_TNC_DSP3', 'DNC_ACCESS_MODE_SENDKEY',
    'DNC_ERROR_LOCATION_NONE', 'DNC_SW_TYPE_TNC_DSP2',
    'IJHCutterPosition', 'DNC_E_NO_PROGRAM', 'DNC_TRIG_ALWAYS',
    'DNC_CNC_TYPE_TURNPLUS', 'DNC_PRG_EVT_SELECT_CLEARED',
    'DNC_STATE_MACHINE_IS_AVAILABLE', 'DNC_INTERFACE_TNCTABLE',
    'DNC_E_MISSING_PARAM', 'DNC_CP_SSH_IDENT_PASSWORD',
    'DNC_TRACE_VARIABLE_ID_SDIFF', 'DNC_EG_PLC', 'DNC32_E_OPTION_VAL',
    'JHTrigger', 'DNC_E_OPTION_NOT_AVAILABLE', 'DNC_E_FILE_EXISTS',
    'JHProgramPositionList', 'DNC_DATA_UNIT_MILLIMETER',
    'IJHFileAttributes', 'JHToolId', 'DNC_PRG_EVT_ERROR_CLEARED',
    'DNC_PLC_SIZE', 'DNC_SW_TYPE_UNKNOWN',
    'DNC_INTERFACE_JHCONFIGURATION', 'DNC_E_COLLISION',
    'DNC_CP_SSH_REMOTE_HOST_KEY_FINGERPRINT', 'JHPlc',
    'DNC_E_NO_DRIVE_ACCESS', 'JHErrorEntry', 'IJHDataAccess3',
    'DNC_MODE_REMOTE', 'DNC_CP_LSV_RX_TIMEOUT',
    'IJHTraceVariableList', 'DNC32_E_STILL_CONN', 'DNC_EC_ERROR',
    'DNC_AXISTYPE_AUX_LINEAR', 'JHFileSystem',
    'DNC_E_FILE_REMOTE_FILENAME', 'DNC_DATA_UNIT_OTHER',
    'JHSoftwareVersion', 'JHDirectoryEntryList', 'DNC_PLC_SIZE_BIT',
    'DNC_ERROR_LOCATION_EDIT', 'DNC_E_RECORD_NOT_FOUND',
    'DNC_CP_PORT', 'JHCutterLocation', 'DNC_SW_TYPE_FS_CCU',
    'DNC_AXISTYPE_SPINDLE', 'JHTrace', 'DNC32_E_FAIL_CONNECT',
    'DNC_TRIG_ON_COND_GT', 'DNC_STATE_DNC_IS_AVAILABLE',
    'DNC_PLC_TYPE', 'DNC_PRG_STS_FINISHED', 'IJHToolId',
    'IJHChannelInfoList', 'IJHError', 'DNC_SW_TYPE_TNC_DSPSG2',
    'DNC_TRACE_VARIABLE_ID_PLC', 'DNC_EC_EMERGENCY_STOP',
    'DNC_TRIG_SAMPLE_MODE', 'IJHTraceVariable',
    'DNC_DATAENTRY_PROPKIND_DATAWIDTH', 'DNC_SPINDLE_STATE_CW',
    'DNC_ATTRIBUTE_READONLY', 'IJHTrigger', 'DNC_EC_PROGRAMABORT',
    'IJHTriggerCondition', '_IJHDiagnosticsEvents',
    'DNC32_E_VER_TOO_OLD', 'DNC_FILE_OBSERVE_REMOVE',
    'IJHAxesPositionStreaming', 'JHRemoteErrorEvents',
    'DNC_PROGRAMBREAKCONDITION_KIND_IGNORE_PROGRAMMED_STOP',
    'JHAxisPositionEnum', 'DNC_E_IN_USE',
    'DNC_STATE_HOST_IS_NOT_AVAILABLE', 'DNC_ATTRIBUTE_SYSTEM',
    'IJHError2', 'DNC_TRIG_ON_COND_INSIDE',
    'DNC_E_CANNOT_LOAD_PROGRAM', 'IJHAxisPosition',
    'DNC_E_NO_PROGRAM_ACTIVE', 'DNC_DATAENTRY_PROPKIND_DATA',
    'JHDataEntry', 'DNC_PRG_STS_RUNNING', '_IJHErrorEvents',
    'DNC_TRACE_VARIABLE_ID_CSI1', 'DNC_TRIG_MODE',
    'DNC32_E_INVALID_PARAM', 'DNC_E_ECLIPSED', 'DNC_SPINDLE_STATE',
    'DNC_DATA_UNIT_SECOND', 'IJHBreakConditionList',
    'DNC_ATTRIBUTE_DIR', 'IJHMachine2', 'DNC_INTERFACE_JHERROR',
    'DNC_TRIG_ON_COND_EQ', 'DNC_ERROR_LOCATION_OEM',
    '_IJHErrorEvents2', 'DNC_TRIG_INTERFACE_SAMPLING',
    'DNC_PROGRAMBREAKCONDITION_KIND', 'DNC_SW_TYPE_TNC_DSPSG1',
    'DNC_TRIG_SAMPLE_ON_PLC', 'DNC_SW_TYPE_TNC_ICTL2',
    'DNC_PRG_STS_STOPPED', 'DNC_CNC_TYPE_CNCPILOT6xx_NCK',
    'DNC32_E_FAIL_LOOKUP', 'IJHDataEntryProperty2List',
    'DNC_AXISTYPE', 'DNC_EC_FEEDHOLD', 'DNC_CONFIGURE_MODE_ADD',
    'IJHRemoteError', '_DJHAutomaticEvents',
    'DNC_DATAENTRY_PROPKIND_INITIALVALUE', 'DNC_TRIG_INTERFACE',
    'DNC_ATTRIBUTE_HIDDEN', 'DNC_SW_TYPE_MC', 'DNC_DATA_UNIT_SELECT',
    'DNC_DATA_UNIT_DEGREE_PER_SEC2',
    'DNC_DATAENTRY_PROPKIND_UNITTEXT',
    'DNC_DATA_UNIT_MILLIMETER_PER_SEC2', 'JHTraceSampleListList',
    'DNC_CP_LSV_OPTIONS',
    'DNC_POSSAMPLES_LOGGING_SAMPLED_WITH_AUX_AXES',
    'DNC_POSSAMPLES_LOGGING_ENDPOINTS_WITH_AUX_AXES',
    'DNC_E_FILE_IN_USE', 'DNC_EVT_PROGRAM', 'JHRemoteErrorEntry',
    'DNC_EG_NONE', 'JHTraceSampleList', 'DNC_PROT_COM',
    'DNC_TRIG_CONDITION', 'JHAxisPosition',
    'DNC_EVT_STATE_DNC_AVAILABLE', 'IJHProgramPosition',
    'JHDataAccess', 'DNC_EG_PYTHON', 'DNC_PRG_STS_IDLE',
    'DNC_PLC_OPTION_NOSYNC', 'IJHConnectionProperty',
    'IJHCutterLocation2List', 'DNC_ACCESS_MODE_TABLEDATAACCESS',
    'DNC_TRACE_VARIABLE_ID_AACT', 'JHBreakConditionEnum',
    'DNC_STATE_NOT_INITIALIZED', 'DNC_FILE_OBSERVE', 'JHError',
    'DNC32_E_TRANS_FAIL', 'DNC_INTERFACE_JHFILESYSTEM',
    'DNC_PRG_EVT_STOPPED', 'DNC_SW_TYPE_TNC_MODEL', 'IJHConnection3',
    'IJHProcessData', 'DNC_FILE_OBSERVE_REMOVE_ALL',
    'IJHRemoteErrorInternal', 'DNC_AXISTYPE_MAIN_LINEAR',
    'DNC_EVT_STATE_CONNECTION_LOST', 'DNC_TRACE_VARIABLE_ID_SERR',
    'DNC_POSSAMPLES_MOTION_SPLINE',
    'DNC_POSSAMPLES_LOGGING_SAMPLED_WITH_BLOCK_END_WITH_AUX_AXES',
    'DNC_PROGRAMBREAKCONDITION_KIND_DEFAULT', 'DNC_E_READ_ONLY',
    'DNC_CNC_TYPE_TNC6xx_NCK', 'JHDataEntryProperty',
    'FEED_MODE_NORMAL', 'DNC_CP_LSV_AUTODETECT',
    'DNC_TRACE_SOURCE_TYPE', 'DNC_SW_TYPE_TNC_DSPSG3',
    'DNC_PROGRAMBREAKCONDITION_KIND_FORCE_OPTIONAL_STOP',
    'JHCutterPosition', 'DNC_TRACE_VARIABLE_TYPE_UNKNOWN',
    'DNC32_E_NO_ADDRESS', 'DNC_PROT_RPC_SECURE', 'JHDataEntry2List',
    'JHDataEntryPropertyEnum', 'DNC_DATAENTRY_PROPKIND_UNIT',
    'DNC_E_FILE_CANNOT_OPEN', 'DNC_E_NOT_POS_NOW', 'IJHFileSystem',
    'DNC_TRIG_SAMPLE_ON_TIMER', 'IJHDataEntryPropertyList',
    'ITNCTable', 'IJHConfiguration', 'DNC_E_LOCKED',
    'FEED_MODE_RAPID', 'DNC_TRIG_ON_SUSTAINED_CONDITION',
    'DNC_E_WRONG_MODE', 'DNC32_E_NOT_RES', '_IJHDataAccessEvents2',
    'IJHTriggerSampling', 'DNC_DATA_UNIT_DEGREE',
    'DNC_AXISTYPE_MAIN_ROTARY', 'DNC_SW_TYPE_CC',
    'DNC_STATE_MACHINE_IS_SHUTTING_DOWN',
    'DNC_ACCESS_MODE_OEM_ENCRYPTED', 'JHCutterLocation2List',
    '_IJHFileSystemEvents', 'DNC_FEED_MODE', 'DNC_E_ITEM_NOT_FOUND',
    'DNC_ACCESS_MODE_PLC', 'DNC_E_EXISTS', 'DNC_E_FILE_LOCKED',
    'DNC_SPINDLE_STATE_RIGID_TAPPING', 'DNC_E_RPCFAILED',
    'DNC_EXEC_RPF', 'DNC_TRACE_SOURCE_TYPE_PLC', 'JHAutomatic',
    'DNC_STATE_NO_PERMISSION', 'DNC_TRACE_VARIABLE_ID_FEED',
    'DNC_MODE', 'DNC_CNC_TYPE_ATEKM_NCK', 'DNC_E_SUBSCRIPTION_ACTIVE',
    'IJHErrorEntry2', 'IJHDataEntryList',
    'DNC_EVT_STATE_MACHINE_SHUTTING_DOWN', 'IJHAxisPositionListList',
    '_DJHPlcEvents', 'DNC_E_NO_STREAMING_ACTIVE',
    'IJHCutterLocationList', '_IJHTraceEvents', 'IJHErrorEntry',
    'DNC_ATTRIBUTE_MODIFIED', 'JHAxisPositionListEnum',
    'DNC_ACCESS_MODE_TESTUTILITY', 'DNC_ACCESS_MODE_ALL',
    'DNC_TRIG_SEQUENCE_AND', 'IJHMachine4', 'DNC_E_SYNONYM_ACCESS',
    'DNC_SPINDLE_STATE_STOPPED', 'DNC_TRIG_ON_COND_NEQ',
    'DNC_E_TRACING_ACTIVE', 'JHProcessData',
    'DNC_CNC_TYPE_MILLPLUSIT_NCK', 'DNC_E_ENDSWITCH_TRIPPED',
    '_IJHAutomaticEvents', 'DNC_INTERFACE_OBJECT',
    'DNC_E_DIR_REMOTE_EXISTS', 'DNC_ERROR_GROUP', 'JHAxisInfo',
    'DNC_EC_WARNING', 'DNC_PRG_EVT_ERROR', 'DNC_E_NOT_INITIALISED',
    'DNC_SPINDLE_STATE_POS_CTRL', 'DNC_ERROR_LOCATION_MACHINE',
    'DNC_POSSAMPLES_MOTION_TYPE',
    'DNC_PROGRAMBREAKCONDITION_KIND_ON_LINE', 'JHTraceChannelEnum',
    'DNC_CNC_TYPE_MILLPLUS', 'DNC_PLC_ACTION', 'DNC_E_DISK_FULL',
    'DNC_PRG_EVT_INTERRUPTED', 'JHTraceSampleListEnum',
    '_DJHErrorEvents', 'JHAxesPositionStreamingEvents',
    'DNC_SW_TYPE_TNC_ICTL1', 'IJHPositioningResult',
    '_DJHRemoteErrorEvents', 'JHDataEntryList',
    'DNC_TRACE_VARIABLE_ID_ANALOG_OUT', 'DNC_TRIG_ON_COND_OUTSIDE',
    'DNC32_E_RECV_FAIL', 'DNC_ACCESS_MODE_AXESPOSITIONSTREAMING',
    'DNC32_E_CONNECT_LOST', 'DNC_CONFIGURE_MODE_REMOVE',
    'DNC_CONFIGURE_MODE_ALL', 'DNC_EVT_STATE_HOST_NOT_AVAILABLE',
    'JHTriggerEnum', 'DNC_DATA_UNIT_PER_MINUTE',
    'IJHSecureConnectionHelper', 'IJHDataAccess4', 'DNC_CP_STOPBITS',
    'DNC_E_FILE_REMOTE_NOT_FOUND', 'DNC_SW_TYPE_NCKERN',
    'JHDataEntryPropertyList', 'DNC_E_REMOTE_READ_ONLY',
    'JHAxisPositionList', 'JHTraceEvents', 'IJHTraceSampleListList',
    'DNC_E_FILE_LOCAL_OPEN_FAILED', 'DNC32_E_INIT',
    'DNC_DATA_UNIT_METER', 'IJHMachine', 'DNC_E_LOCAL_TO_UTC',
    'DNC_KEYACTION', 'JHCutterLocationEnum',
    'DNC_POSSAMPLES_MOTION_COMPLEX', 'DNC_EG_GENERAL',
    'IJHChannelInfo', 'JHAxesPositionStreaming', 'JHTriggerList',
    'IJHDataEntry', 'DNC_E_OUT_OF_RANGE', 'DNC_INTERFACE_JHTRACE',
    'DNC_E_DIR_OVERFLOW', 'JHTraceVariableEnum', 'JHTraceVariable',
    'JHMachine', 'DNC_E_TRANSFER_ABORT', 'DNC_TRACE_SOURCE_TYPE_CCU',
    'DNC_EVT_STATE_MACHINE_INITIALIZING', 'IJHDataEntry2List',
    'DNC32_E_VER_TOO_NEW',
    'DNC_POSSAMPLES_LOGGING_SAMPLED_WITH_BLOCK_END', 'IJHConnection2',
    'DNC_E_KEY_UNDEFINED', 'JHDataEntryEnum', 'DNC_PRG_EVT_STARTED',
    'DNC_INTERFACE_JHPROCESSDATA', 'IJHTrace', 'DNC_EC_PROGRAMHOLD',
    'JHBreakConditionList', 'JHDataEntryProperty2List',
    'DNC_TRACE_VARIABLE_TYPE_NORMAL', 'DNC_ACCESS_MODE_IPODATAACCESS',
    'DNC_PLC_OPTION', 'IJHMachine3',
    'DNC_DATAENTRY_PROPKIND_SUBSCRIBE_CAPABILITY',
    'DNC_CNC_TYPE_ATEKM', 'DNC_SPINDLE_STATE_CCW',
    'DNC_INTERFACE_JHPLC', 'DNC_EG_REMOTE', 'DNC_CP_SSH_REMOTE_USER',
    'DNC_EXEC_AUTOMATIC', 'DNC_POSSAMPLES_MOTION_CIRCULAR',
    'DNC_EC_RESET', 'DNC_TRACE_SOURCE_TYPE_IPO',
    'JHDiagnosticsEvents', 'DNC_FILE_OBSERVE_ADD',
    'DNC_E_HOST_REJECTED', 'JHChannelInfoEnum', 'IJHDataAccess',
    'DNC_INTERFACE_JHAXESPOSITIONSTREAMING', 'DNC_E_UNABLE_TO_DELETE',
    'JHCutterLocation2Enum', 'IJHTest', 'DNC_STATE',
    'DNC_TRACE_VARIABLE_ID_ANOM', 'DNC_E_RECORD_LOCKED',
    'DNC_DATA_UNIT_INCH', 'DNC_TRIG_MODE_NONE',
    'DNC_ACCESS_MODE_DEFAULT', 'JHToolId0', 'DNC_E_FAIL',
    'JHVirtualMachine', 'JHProgramPositionEnum', 'IJHAxisInfo',
    'DNC_TRACE_VARIABLE_TYPE', 'IJHCutterLocation2',
    'DNC_ACCESS_MODE', 'DNC_ACCESS_MODE_INSPECT',
    'IJHSoftwareVersionList', 'DNC32_E_FAIL_ACCEPT', 'typelib_path',
    'DNC_CONFIGURE_MODE', 'DNC_CP_DIO_FLOWCTRL',
    'DNC_INTERFACE_JHVERSION', 'DNC_TRIG_SAMPLE_ON_CCU',
    'DNC_E_INVALID_PARAM', 'JHChannelInfoList',
    'DNC_POSSAMPLES_LOGGING_ENDPOINTS', 'DNC_EVT_STATE_DNC_STOPPED',
    'IJHTraceSample', 'JHDiagnostics', 'IJHConnectionList',
    'DNC_CP_DATABITS', 'DNC32_E_RECV_TIMEOUT',
    'DNC_PROT_TCPIP_SECURE', 'DNC_CNC_TYPE_GRINDPLUS_NCK',
    'DNC_TRACE_VARIABLE_ID_CCDBG', 'DNC_DATA_UNIT_SELECT_INCH',
    'DNC_DATA_UNIT_DEGREES_PER_MINUTE', 'JHErrorEntry2List',
    'DNC_E_STREAMING_ACTIVE', 'DNC_INTERFACE_JHAUTOMATIC',
    'DNC_E_NOT_LOCKED', 'DNC_INTERFACE_JHDIAGNOSTICS',
    'JHDirectoryEntry', 'JHTraceChannelList', '_IJHRemoteErrorEvents',
    'IJHAutomatic', 'DNC_DATAENTRY_PROPKIND_DESCRIPTION',
    'DNC_E_CANNOT_START_PROGRAM', 'JHProgramPosition',
    'DNC_DATA_UNIT_DEGREE_PER_SEC4', 'DNC_ACCESS_MODE_DNC',
    '_DJHTraceEvents', 'DNC_STATE_HOST_IS_STOPPED',
    'DNC_EVT_STATE_PERMISSION_DENIED', 'DNC_CP_HOST',
    'DNC_DATA_UNIT_METER_PER_SEC2', 'DNC_CP_PARITY',
    'JHSoftwareVersionList', 'DNC_DATAENTRY_PROPKIND_LOCATION',
    'DNC_TRACE_VARIABLE_ID_SNOM', 'DNC_PLC_SIZE_BYTE',
    'DNC_E_FILE_NOT_FOUND', 'DNC_E_UNABLE_TO_SET',
    'DNC_DATA_UNIT_VOLT', 'DNC_TRIG_SEQUENCE_OR', 'DNC_CP_CHECK_DTR',
    'JHDataAccessEvents', 'DNC_MODE_LOCAL', 'JHChannelInfo',
    'JHErrorEntry2Enum', 'DNC_ACCESS_MODE_MONITOR',
    'DNC_TRACE_SOURCE_TYPE_UNKNOWN', 'JHAxisPositionListList',
    'DNC_DATA_UNIT_DEGREE_PER_SEC', 'JHMachineEvents2',
    '_IJHAutomaticEvents3', 'DNC_CP_LSV_RETRIES',
    'JHSoftwareVersionEnum', 'DNC_E_DNC_PROHIBITED',
    'DNC_E_UNABLE_TO_GET', 'DNC_E_TIMEOUT', 'DNC_E_LIST_EMPTY',
    'DNC_DATA_UNIT_SELECT_METRIC', 'DNC_CONFIGURE_MODE_CHANGE',
    'IJHErrorInternal2', 'IJHErrorEntry2List',
    'DNC_TRACE_VARIABLE_TYPE_CHANNEL', 'IJHBreakCondition',
    'DNC_CP_DIO_PROTOCOL', 'DNC_TRACE_VARIABLE_ID_IPOLOGIC',
    'IJHAxisInfoList', '_IJHAutomaticEvents2',
    'DNC_E_FILE_WRONG_MODE', 'IJHDataEntry2',
    'DNC_STATE_DNC_IS_STOPPED', 'DNC_EXEC_SIMULO_TURBO_DEPRECATED',
    'JHAxisInfoList', 'DNC_PLC_TYPE_MARKER',
    'DNC_TRACE_VARIABLE_ID_CSI2', 'DNC32_E_NOT_PROT',
    'DNC_DATAENTRY_PROPKIND', 'DNC_TRIG_SEQUENCE',
    'DNC_INTERFACE_JHTEST', 'DNC_STATE_MACHINE_IS_BOOTED',
    'DNC_DATAENTRY_PROPKIND_LOWER_BOUND', 'IJHSoftwareVersion',
    'DNC_SW_TYPE_MP_UIMS', 'JHRemoteError', 'JHErrorEvents',
    'JHErrorEntryList', 'DNC_E_FILE_OPEN_FAILED'
]

